version: '3'

services:
    teamcity:
        image: sjoerdmulder/teamcity
        ports:
            - 8111
    teamcity-agent:
        image: sjoerdmulder/teamcity-agent
        environment:
            - TEAMCITY_SERVER=http://teamcity:8111
    postgres:
        image: postgres
        environment:
            - POSTGRES_DB=teamcity
            - POSTGRES_PASSWORD=password
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - teamcity
        ports:
            - "4000:4000"